---
- name: Git clone Drupal Projects
  git:
    repo: "{{ item.value.url|default(drulenium_drupal_git_url) }}/{{ item.key }}.git"
    dest: "{{ drulenium_hostmaster_root }}/{{ drulenium_module_path }}/{{ item.key }}"
    depth: 1 # speeds things up
    version: "{{ item.value.version }}"
    update: "{{ item.value.keep_updated|default('no') }}"
  with_dict: "{{ drulenium_modules }}"
  become: yes
  become_user: "{{ aegir_user }}"

- name: Git clone Selenium WebDriver PHP bindings
  git:
    repo: "{{ item.value.url }}"
    dest: "{{ drulenium_hostmaster_root }}/{{ drulenium_library_path }}/{{ item.key }}"
    depth: 1 # speeds things up
    version: "{{ item.value.version }}"
    update: "{{ item.value.keep_updated|default('no') }}"
  with_dict: "{{ drulenium_libraries }}"
  become: yes
  become_user: "{{ aegir_user }}"

