---
- name: Clear global Drush cache
  command: drush @none cc drush
  become: yes
  become_user: "{{ aegir_user }}"

- name: Clear all hostmaster caches
  command: drush @hostmaster cc all
  become: yes
  become_user: "{{ aegir_user }}"

- name: Verify Aegir front-end
  shell: drush @hm cc drush && drush @hm hosting-task @hostmaster verify --force
  become: yes
  become_user: "{{ aegir_user }}"
